language: node_js
node_js:
  - 14
install: npm install
services:
  - postgresql
before_script:
  - psql -c 'create database survey_test;' -U postgres
script: npm run test:ci

notifications:
  email: false